"""Single source of truth for checkout plan data."""
from __future__ import annotations

CHECKOUT_PLANS: dict[str, dict] = {
    "growth": {
        "id": "growth",
        "mode": "card",
        "title": "Growth Plan",
        "tagline": "Scale your retail operations with data-driven insights.",
        "badge": None,
        "inner_plan_name": None,
        "price": "1,000",
        "price_unit": "THB/mo",
        "features": [
            "ML revenue predictions",
            "Advanced AI advisory",
            "Full retailer dashboard",
            "Priority Support",
            "Traffic analytics",
        ],
        "show_order_summary": False,
        "subtotal": None,
        "vat_label": None,
        "vat": None,
        "total": None,
        "security_eyebrow": "ENTERPRISE GRADE",
        "security_text": "Secure Intelligence Guarantee",
        "pay_label": "Pay 1,000 THB",
        "show_save_checkbox": False,
        "show_legal_text": False,
        "legal_text": None,
        "show_card_icons": False,
        "show_gateway_note": True,
        "gateway_text": "Secure encrypted transaction via PTG Gateway",
        "show_media_images": True,
    },
    "pro": {
        "id": "pro",
        "mode": "split",
        "title": "Complete your upgrade",
        "tagline": "Get full access to the Pro Plan and unlock advanced retail intelligence tools.",
        "badge": "PROFESSIONAL",
        "inner_plan_name": "Pro Plan",
        "price": "499",
        "price_unit": "/ month",
        "features": [
            "AI recommendations",
            "Traffic analytics",
            "Priority Support",
            "Real-time alerts",
        ],
        "show_order_summary": True,
        "subtotal": "499.00 THB",
        "vat_label": "VAT (0%)",
        "vat": "0.00 THB",
        "total": "499.00 THB",
        "security_eyebrow": None,
        "security_text": "Your transaction is secured with 256-bit SSL encryption and monitored for potential fraud.",
        "pay_label": "Pay 499 THB",
        "show_save_checkbox": True,
        "show_legal_text": True,
        "legal_text": 'By clicking "Pay 499 THB", you agree to our Terms of Service and Subscription Policy.',
        "show_card_icons": True,
        "show_gateway_note": False,
        "gateway_text": None,
        "show_media_images": False,
    },
}
